name: Python script

on:
  ## Triggers the workflow on push or pull request events but only for the "main" branch
#   push:
#     branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run a python script - Test
        env:
          XRAY_SECRET: ${{ secrets.XRAY_SECRET  }}
          XRAY_ID: ${{  vars.XRAY_ID  }}
        run: |
            python .github/workflows/example.py
            python -m behavex --tags=sample_tag
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: output/
